console.log("----------------Step 1--------------");
var sweety="Sweety";
console.log(sweety);
var cutie="Cutie";
console.log(cutie);
var temp= sweety;
sweety=cutie;
console.log(temp);
cutie=temp;
console.log(temp);

console.log("------------step 2-------------");
var num1= 100;
console.log("num1 value is:",num1);
var num2=200;
console.log("num2 value is:",num2);
var num3=300;
console.log("num3 value is:",num3);
num1=num2;
num2=num3;
num3=temp2;
console.log("temp2 file is",temp2);
